#pragma config(Sensor, S3,     HTRCX,          sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/**
 * hitechnic-irlink-rcx.h provides an API for the HiTechnic IR Link Sensor to allow
 * communication between the NXT and RCX.
 *
 * Changelog:
 * - 0.1: Initial release
 *
 * Credits:
 * - Big thanks to HiTechnic for providing me with the hardware necessary to write and test this.
 * - Big thanks to Thorsten Benter for giving me one of his RCXs to work with!
 *
 * License: You may use this code as you wish, provided you give credit where it's due.
 *
 * THIS CODE WILL ONLY WORK WITH ROBOTC VERSION 4.10 AND HIGHER

 * Xander Soldaat (xander_at_botbench.com)
 * 16 September 2010
 * version 0.1
 *
 * DESCRIPTION:
 * This code waits to receive an IR signal from an RCX.
 * Once the signal is received, pressing Enter will display all 16 bytes of any message received.
 * Press the Enter button repeatedly to display all 16 bytes separated into 3 pages. (Fourth press clears screen.)
 * If the Enter button is pressed before a message is received, the byte values should all be zero.
 *
 * Index 8 of the message (i.e. "msg[8]"), can be used to identify simple numeric messages sent from teh RCX.
 */

#include "hitechnic-irlink-rcx.h"

task main () {
	short page = 0;
  tByteArray msg;
  eraseDisplay();
  displayCenteredBigTextLine(2, "RCX IR");
  displayCenteredBigTextLine(4, "Receiver");
  sleep(3000);
  eraseDisplay();
  while(true) {
  	// Read the message from the RCX and display
  	HTRCXreadResp(HTRCX, msg);

    while(nNxtButtonPressed != kEnterButton) sleep(1);	//wait for button press
    while(nNxtButtonPressed != kNoButton) sleep(1);			//wait for button release
    page++;
    if(page == 1) {
    	eraseDisplay();
    	playSound(soundBlip);
    	displayCenteredTextLine(1, "Page_%d", 1);
	    displayTextLine(2, "%d", msg[0]);
	    displayTextLine(3, "%d", msg[1]);
	    displayTextLine(4, "%d", msg[2]);
	    displayTextLine(5, "%d", msg[3]);
	    displayTextLine(6, "%d", msg[4]);
	    displayTextLine(7, "%d", msg[5]);
	  }
	  else if(page == 2) {
	  	eraseDisplay();
	  	playSound(soundBlip);
	  	displayCenteredTextLine(1, "Page_%d", 2);
		  displayTextLine(2, "%d", msg[6]);
		  displayTextLine(3, "%d", msg[7]);
		  displayTextLine(4, "%d", msg[8]);
		  displayTextLine(5, "%d", msg[9]);
		  displayTextLine(6, "%d", msg[10]);
		  displayTextLine(7, "%d", msg[11]);
		}
		else if(page == 3) {
			eraseDisplay();
			playSound(soundBlip);
			displayCenteredTextLine(1, "Page_%d", 3);
			displayTextLine(2, "%d", msg[12]);
	    displayTextLine(3, "%d", msg[13]);
	    displayTextLine(4, "%d", msg[14]);
	    displayTextLine(5, "%d", msg[15]);
	  }
	  else if(page > 3) {
	  	eraseDisplay();
	  	page = 0;
	  }
  }
}
