#pragma config(Sensor, S1,     Touch,               sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//////////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                     Test RCX Infrared Messaging
//
// This short little program tests the RCX infrared messaging capability.
//
// The ROBOTC IDE has a debugger window that can generate message numbers #1 to #6. If this program is
// running when one of these six message values is sent, then it will play a different tone for each message.
//
// The program loops forever.
//
//////////////////////////////////////////////////////////////////////////////////////////////////////////

#pragma platform(RCX)

int nMsgCount = 0;
int buttonState = 0;


task main()
{
	//wait until button press
	while (true)
	{
		if (SensorValue[Touch] != 0 && buttonState == 0)
		{
		  PlaySound(soundBeepBeep);
		  nMsgCount++;
		  buttonState = 1;
		  SetUserDisplay(nMsgCount);
		  sendMessageWithParm(nMsgCount);
		}
		else if (SensorValue[Touch] == 0 && buttonState != 0)
		{
		  PlaySound(soundBlip);
		  buttonState = 0;
	  }
	}
}
